In [13]:
import requests
from bs4 import BeautifulSoup
from pandas import DataFrame
import pandas as pd
import numpy as np
import time

def result_type(df, *col):
    if df[col[0]] > df[col[1]]:
        if df['type'] == 'SO':
            return 4
        else:
            return 1
    elif df['type'] == 'OT':
        return 3
    return 2

df = DataFrame()

for year in range(2008, 2019, 1):
    r = requests.get(f'https://www.hockey-reference.com/leagues/NHL_{year}_games.html')
    soup = BeautifulSoup(r.content, 'html.parser')
    
    df = pd.concat([df, DataFrame(np.array([ele.get_text() for ele in soup.select('#games > tbody > tr > .')]).reshape(-1, 9)) \
        .drop(columns=[0, 6, 7, 8], axis=1) \
        .rename(columns={1: 'away', 2: 'away_goals', 3: 'home', 4: 'home_goals', 5: 'type'}) \
        .assign(away_result=lambda x: x.apply(result_type, args=['away_goals', 'home_goals'], axis=1),
                home_result=lambda x: x.apply(result_type, args=['home_goals', 'away_goals'], axis=1),
                year=f'{year}') \
        .drop(columns=['type'])])
    time.sleep(2)

In [14]:
df = df \
    .loc[lambda x: x['away_goals'] != ''] \
    .reset_index(drop=True) \
    .reset_index() \
    .rename(columns={'index': 'id'}) \
    .assign(id=lambda x: x['id'] + 1)

In [46]:
teams = DataFrame(df['home'].str.split(' ').str[-1].unique(), columns=['team']) \
        .sort_values('team') \
        .reset_index(drop=True) \
        .reset_index() \
        .rename(columns={'index': 'id'}) \
        .assign(id=lambda x: x['id'] + 1)
teams

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>team</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Avalanche</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>Blackhawks</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>Blues</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>Bruins</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>Canadiens</td>
    </tr>
    <tr>
      <th>5</th>
      <td>6</td>
      <td>Canucks</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>Capitals</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>Coyotes</td>
    </tr>
    <tr>
      <th>8</th>
      <td>9</td>
      <td>Devils</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10</td>
      <td>Ducks</td>
    </tr>
    <tr>
      <th>10</th>
      <td>11</td>
      <td>Flames</td>
    </tr>
    <tr>
      <th>11</th>
      <td>12</td>
      <td>Flyers</td>
    </tr>
    <tr>
      <th>12</th>
      <td>13</td>
      <td>Hurricanes</td>
    </tr>
    <tr>
      <th>13</th>
      <td>14</td>
      <td>Islanders</td>
    </tr>
    <tr>
      <th>14</th>
      <td>15</td>
      <td>Jackets</td>
    </tr>
    <tr>
      <th>15</th>
      <td>16</td>
      <td>Jets</td>
    </tr>
    <tr>
      <th>16</th>
      <td>17</td>
      <td>Kings</td>
    </tr>
    <tr>
      <th>17</th>
      <td>18</td>
      <td>Knights</td>
    </tr>
    <tr>
      <th>18</th>
      <td>19</td>
      <td>Leafs</td>
    </tr>
    <tr>
      <th>19</th>
      <td>20</td>
      <td>Lightning</td>
    </tr>
    <tr>
      <th>20</th>
      <td>21</td>
      <td>Oilers</td>
    </tr>
    <tr>
      <th>21</th>
      <td>22</td>
      <td>Panthers</td>
    </tr>
    <tr>
      <th>22</th>
      <td>23</td>
      <td>Penguins</td>
    </tr>
    <tr>
      <th>23</th>
      <td>24</td>
      <td>Predators</td>
    </tr>
    <tr>
      <th>24</th>
      <td>25</td>
      <td>Rangers</td>
    </tr>
    <tr>
      <th>25</th>
      <td>26</td>
      <td>Sabres</td>
    </tr>
    <tr>
      <th>26</th>
      <td>27</td>
      <td>Senators</td>
    </tr>
    <tr>
      <th>27</th>
      <td>28</td>
      <td>Sharks</td>
    </tr>
    <tr>
      <th>28</th>
      <td>29</td>
      <td>Stars</td>
    </tr>
    <tr>
      <th>29</th>
      <td>30</td>
      <td>Thrashers</td>
    </tr>
    <tr>
      <th>30</th>
      <td>31</td>
      <td>Wild</td>
    </tr>
    <tr>
      <th>31</th>
      <td>32</td>
      <td>Wings</td>
    </tr>
  </tbody>
</table>
</div>

In [52]:
playoffs = DataFrame()

for year in range(2018, 2016, -1):
    r = requests.get(f'https://www.hockey-reference.com/leagues/NHL_2018.html')
    soup = BeautifulSoup(r.content, 'html.parser')
    
    playoffs = pd.concat([playoffs, 
                          pd.concat([DataFrame([ele.get_text() for ele in soup.select('#standings_EAS > tbody > tr > th')]),
                                     DataFrame([ele.get_text() for ele in soup.select('#standings_WES > tbody > tr > th')])
                                    ]) \
                            .assign(playoffs=lambda x: x.iloc[:, 0].str.endswith('*').astype(int),
                                    year=f'{year}',
                                    team=lambda x: x.iloc[:, 0].str.split(' ').str[-1].str.replace('*', '')) \
                            .merge(teams, left_on='team', right_on='team') \
                            .drop(columns=[0, 'team']) \
                            .rename(columns={'id': 'team_id'}) \
                            [['team_id', 'year', 'playoffs']]
                            
              ])
playoffs

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>team_id</th>
      <th>year</th>
      <th>playoffs</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>20</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>4</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>19</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>22</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>32</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>5</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>27</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>26</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>7</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>23</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>10</th>
      <td>12</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>11</th>
      <td>15</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>12</th>
      <td>9</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>13</th>
      <td>13</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>14</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>15</th>
      <td>25</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>24</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>17</th>
      <td>16</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>18</th>
      <td>31</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>20</th>
      <td>3</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>29</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>2</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>18</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24</th>
      <td>10</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25</th>
      <td>28</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>26</th>
      <td>17</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>27</th>
      <td>11</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>21</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>29</th>
      <td>6</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>4</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>19</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>22</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>32</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>5</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>27</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>26</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>7</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>23</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>10</th>
      <td>12</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>11</th>
      <td>15</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>12</th>
      <td>9</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>13</th>
      <td>13</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>14</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>15</th>
      <td>25</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>24</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>17</th>
      <td>16</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>18</th>
      <td>31</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>20</th>
      <td>3</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>29</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>2</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>18</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24</th>
      <td>10</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25</th>
      <td>28</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>26</th>
      <td>17</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>27</th>
      <td>11</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>21</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>29</th>
      <td>6</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>30</th>
      <td>8</td>
      <td>2017</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>62 rows × 3 columns</p>
</div>

In [53]:
playoffs = playoffs \
    .reset_index(drop=True) \
    .reset_index() \
    .rename(columns={'index': 'id'}) \
    .assign(id=lambda x: x['id'] + 1)
playoffs

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>team_id</th>
      <th>year</th>
      <th>playoffs</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>20</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>4</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>19</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>22</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>32</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>6</td>
      <td>5</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>27</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>26</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>9</td>
      <td>7</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10</td>
      <td>23</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>10</th>
      <td>11</td>
      <td>12</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>11</th>
      <td>12</td>
      <td>15</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>12</th>
      <td>13</td>
      <td>9</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>13</th>
      <td>14</td>
      <td>13</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>15</td>
      <td>14</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>15</th>
      <td>16</td>
      <td>25</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>17</td>
      <td>24</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>17</th>
      <td>18</td>
      <td>16</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>18</th>
      <td>19</td>
      <td>31</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>19</th>
      <td>20</td>
      <td>1</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>20</th>
      <td>21</td>
      <td>3</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>22</td>
      <td>29</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>23</td>
      <td>2</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>24</td>
      <td>18</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24</th>
      <td>25</td>
      <td>10</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25</th>
      <td>26</td>
      <td>28</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>26</th>
      <td>27</td>
      <td>17</td>
      <td>2018</td>
      <td>1</td>
    </tr>
    <tr>
      <th>27</th>
      <td>28</td>
      <td>11</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>29</td>
      <td>21</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>29</th>
      <td>30</td>
      <td>6</td>
      <td>2018</td>
      <td>0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>32</th>
      <td>33</td>
      <td>4</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>33</th>
      <td>34</td>
      <td>19</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>34</th>
      <td>35</td>
      <td>22</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>35</th>
      <td>36</td>
      <td>32</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>36</th>
      <td>37</td>
      <td>5</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>37</th>
      <td>38</td>
      <td>27</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>38</th>
      <td>39</td>
      <td>26</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>39</th>
      <td>40</td>
      <td>7</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>40</th>
      <td>41</td>
      <td>23</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>41</th>
      <td>42</td>
      <td>12</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>42</th>
      <td>43</td>
      <td>15</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>43</th>
      <td>44</td>
      <td>9</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>44</th>
      <td>45</td>
      <td>13</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>45</th>
      <td>46</td>
      <td>14</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>46</th>
      <td>47</td>
      <td>25</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>47</th>
      <td>48</td>
      <td>24</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>48</th>
      <td>49</td>
      <td>16</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>49</th>
      <td>50</td>
      <td>31</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>50</th>
      <td>51</td>
      <td>1</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>51</th>
      <td>52</td>
      <td>3</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>52</th>
      <td>53</td>
      <td>29</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>53</th>
      <td>54</td>
      <td>2</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>54</th>
      <td>55</td>
      <td>18</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>55</th>
      <td>56</td>
      <td>10</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>56</th>
      <td>57</td>
      <td>28</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>57</th>
      <td>58</td>
      <td>17</td>
      <td>2017</td>
      <td>1</td>
    </tr>
    <tr>
      <th>58</th>
      <td>59</td>
      <td>11</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>59</th>
      <td>60</td>
      <td>21</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>60</th>
      <td>61</td>
      <td>6</td>
      <td>2017</td>
      <td>0</td>
    </tr>
    <tr>
      <th>61</th>
      <td>62</td>
      <td>8</td>
      <td>2017</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>62 rows × 4 columns</p>
</div>

In [18]:
schedule = df[['id', 'year', 'away', 'home']] \
        .assign(away=lambda x: x['away'].str.split(' ').str[-1]) \
        .assign(home=lambda x: x['home'].str.split(' ').str[-1]) \
        .merge(teams[['id', 'team']], left_on='away', right_on='team') \
        .merge(teams[['id', 'team']], left_on='home', right_on='team')  \
        [['id_x', 'year', 'id_y', 'id']] \
        .rename(columns={'id_x': 'id', 'id_y': 'away_id', 'id': 'home_id'}) \
        .sort_values('id') \
        .reset_index(drop=True)
schedule

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>year</th>
      <th>away_id</th>
      <th>home_id</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>2008</td>
      <td>10</td>
      <td>17</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>2008</td>
      <td>17</td>
      <td>10</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>2008</td>
      <td>5</td>
      <td>13</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>2008</td>
      <td>29</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>2008</td>
      <td>10</td>
      <td>32</td>
    </tr>
    <tr>
      <th>5</th>
      <td>6</td>
      <td>2008</td>
      <td>27</td>
      <td>19</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>2008</td>
      <td>12</td>
      <td>11</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>2008</td>
      <td>28</td>
      <td>21</td>
    </tr>
    <tr>
      <th>8</th>
      <td>9</td>
      <td>2008</td>
      <td>2</td>
      <td>31</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10</td>
      <td>2008</td>
      <td>1</td>
      <td>24</td>
    </tr>
    <tr>
      <th>10</th>
      <td>11</td>
      <td>2008</td>
      <td>22</td>
      <td>25</td>
    </tr>
    <tr>
      <th>11</th>
      <td>12</td>
      <td>2008</td>
      <td>19</td>
      <td>27</td>
    </tr>
    <tr>
      <th>12</th>
      <td>13</td>
      <td>2008</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <th>13</th>
      <td>14</td>
      <td>2008</td>
      <td>9</td>
      <td>20</td>
    </tr>
    <tr>
      <th>14</th>
      <td>15</td>
      <td>2008</td>
      <td>7</td>
      <td>30</td>
    </tr>
    <tr>
      <th>15</th>
      <td>16</td>
      <td>2008</td>
      <td>14</td>
      <td>26</td>
    </tr>
    <tr>
      <th>16</th>
      <td>17</td>
      <td>2008</td>
      <td>23</td>
      <td>13</td>
    </tr>
    <tr>
      <th>17</th>
      <td>18</td>
      <td>2008</td>
      <td>10</td>
      <td>15</td>
    </tr>
    <tr>
      <th>18</th>
      <td>19</td>
      <td>2008</td>
      <td>4</td>
      <td>29</td>
    </tr>
    <tr>
      <th>19</th>
      <td>20</td>
      <td>2008</td>
      <td>28</td>
      <td>6</td>
    </tr>
    <tr>
      <th>20</th>
      <td>21</td>
      <td>2008</td>
      <td>6</td>
      <td>11</td>
    </tr>
    <tr>
      <th>21</th>
      <td>22</td>
      <td>2008</td>
      <td>32</td>
      <td>2</td>
    </tr>
    <tr>
      <th>22</th>
      <td>23</td>
      <td>2008</td>
      <td>12</td>
      <td>21</td>
    </tr>
    <tr>
      <th>23</th>
      <td>24</td>
      <td>2008</td>
      <td>9</td>
      <td>22</td>
    </tr>
    <tr>
      <th>24</th>
      <td>25</td>
      <td>2008</td>
      <td>3</td>
      <td>17</td>
    </tr>
    <tr>
      <th>25</th>
      <td>26</td>
      <td>2008</td>
      <td>15</td>
      <td>31</td>
    </tr>
    <tr>
      <th>26</th>
      <td>27</td>
      <td>2008</td>
      <td>29</td>
      <td>24</td>
    </tr>
    <tr>
      <th>27</th>
      <td>28</td>
      <td>2008</td>
      <td>26</td>
      <td>14</td>
    </tr>
    <tr>
      <th>28</th>
      <td>29</td>
      <td>2008</td>
      <td>25</td>
      <td>27</td>
    </tr>
    <tr>
      <th>29</th>
      <td>30</td>
      <td>2008</td>
      <td>4</td>
      <td>8</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>13031</th>
      <td>13032</td>
      <td>2018</td>
      <td>18</td>
      <td>21</td>
    </tr>
    <tr>
      <th>13032</th>
      <td>13033</td>
      <td>2018</td>
      <td>4</td>
      <td>22</td>
    </tr>
    <tr>
      <th>13033</th>
      <td>13034</td>
      <td>2018</td>
      <td>31</td>
      <td>17</td>
    </tr>
    <tr>
      <th>13034</th>
      <td>13035</td>
      <td>2018</td>
      <td>19</td>
      <td>9</td>
    </tr>
    <tr>
      <th>13035</th>
      <td>13036</td>
      <td>2018</td>
      <td>25</td>
      <td>14</td>
    </tr>
    <tr>
      <th>13036</th>
      <td>13037</td>
      <td>2018</td>
      <td>13</td>
      <td>12</td>
    </tr>
    <tr>
      <th>13037</th>
      <td>13038</td>
      <td>2018</td>
      <td>1</td>
      <td>28</td>
    </tr>
    <tr>
      <th>13038</th>
      <td>13039</td>
      <td>2018</td>
      <td>8</td>
      <td>6</td>
    </tr>
    <tr>
      <th>13039</th>
      <td>13040</td>
      <td>2018</td>
      <td>11</td>
      <td>16</td>
    </tr>
    <tr>
      <th>13040</th>
      <td>13041</td>
      <td>2018</td>
      <td>24</td>
      <td>7</td>
    </tr>
    <tr>
      <th>13041</th>
      <td>13042</td>
      <td>2018</td>
      <td>29</td>
      <td>10</td>
    </tr>
    <tr>
      <th>13042</th>
      <td>13043</td>
      <td>2018</td>
      <td>3</td>
      <td>2</td>
    </tr>
    <tr>
      <th>13043</th>
      <td>13044</td>
      <td>2018</td>
      <td>27</td>
      <td>23</td>
    </tr>
    <tr>
      <th>13044</th>
      <td>13045</td>
      <td>2018</td>
      <td>26</td>
      <td>20</td>
    </tr>
    <tr>
      <th>13045</th>
      <td>13046</td>
      <td>2018</td>
      <td>10</td>
      <td>8</td>
    </tr>
    <tr>
      <th>13046</th>
      <td>13047</td>
      <td>2018</td>
      <td>27</td>
      <td>4</td>
    </tr>
    <tr>
      <th>13047</th>
      <td>13048</td>
      <td>2018</td>
      <td>20</td>
      <td>13</td>
    </tr>
    <tr>
      <th>13048</th>
      <td>13049</td>
      <td>2018</td>
      <td>18</td>
      <td>11</td>
    </tr>
    <tr>
      <th>13049</th>
      <td>13050</td>
      <td>2018</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>13050</th>
      <td>13051</td>
      <td>2018</td>
      <td>14</td>
      <td>32</td>
    </tr>
    <tr>
      <th>13051</th>
      <td>13052</td>
      <td>2018</td>
      <td>6</td>
      <td>21</td>
    </tr>
    <tr>
      <th>13052</th>
      <td>13053</td>
      <td>2018</td>
      <td>26</td>
      <td>22</td>
    </tr>
    <tr>
      <th>13053</th>
      <td>13054</td>
      <td>2018</td>
      <td>29</td>
      <td>17</td>
    </tr>
    <tr>
      <th>13054</th>
      <td>13055</td>
      <td>2018</td>
      <td>15</td>
      <td>24</td>
    </tr>
    <tr>
      <th>13055</th>
      <td>13056</td>
      <td>2018</td>
      <td>25</td>
      <td>12</td>
    </tr>
    <tr>
      <th>13056</th>
      <td>13057</td>
      <td>2018</td>
      <td>31</td>
      <td>28</td>
    </tr>
    <tr>
      <th>13057</th>
      <td>13058</td>
      <td>2018</td>
      <td>5</td>
      <td>19</td>
    </tr>
    <tr>
      <th>13058</th>
      <td>13059</td>
      <td>2018</td>
      <td>2</td>
      <td>16</td>
    </tr>
    <tr>
      <th>13059</th>
      <td>13060</td>
      <td>2018</td>
      <td>9</td>
      <td>7</td>
    </tr>
    <tr>
      <th>13060</th>
      <td>13061</td>
      <td>2018</td>
      <td>22</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
<p>13061 rows × 4 columns</p>
</div>

In [19]:
away = df.loc[:, ['id', 'year', 'away', 'away_goals', 'away_result']] \
        .rename(columns={'away': 'team', 'away_goals': 'goals', 'away_result': 'result_id'})
home = df.loc[:, ['id', 'year', 'home', 'home_goals', 'home_result']] \
    .rename(columns={'home': 'team', 'home_goals': 'goals', 'home_result': 'result_id'})

results = pd.concat([away, home]) \
    .assign(team=lambda x: x['team'].str.split(' ').str[-1]) \
    .merge(teams, left_on='team', right_on='team') \
    .drop(columns=['team']) \
    .rename(columns={'id_x': 'game_id', 'id_y': 'team_id'}) \
    .sort_values('game_id') \
    .reset_index() \
    .rename(columns={'index': 'id'}) \
    [['id', 'game_id', 'year', 'team_id', 'goals', 'result_id']] \
    .sort_values('id')
results

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>game_id</th>
      <th>year</th>
      <th>team_id</th>
      <th>goals</th>
      <th>result_id</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>1</td>
      <td>2008</td>
      <td>10</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1</td>
      <td>5</td>
      <td>2008</td>
      <td>10</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>34</th>
      <td>2</td>
      <td>18</td>
      <td>2008</td>
      <td>10</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>61</th>
      <td>3</td>
      <td>31</td>
      <td>2008</td>
      <td>10</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>207</th>
      <td>4</td>
      <td>104</td>
      <td>2008</td>
      <td>10</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>247</th>
      <td>5</td>
      <td>124</td>
      <td>2008</td>
      <td>10</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>390</th>
      <td>6</td>
      <td>196</td>
      <td>2008</td>
      <td>10</td>
      <td>5</td>
      <td>1</td>
    </tr>
    <tr>
      <th>529</th>
      <td>7</td>
      <td>265</td>
      <td>2008</td>
      <td>10</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <th>571</th>
      <td>8</td>
      <td>286</td>
      <td>2008</td>
      <td>10</td>
      <td>2</td>
      <td>4</td>
    </tr>
    <tr>
      <th>604</th>
      <td>9</td>
      <td>303</td>
      <td>2008</td>
      <td>10</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>692</th>
      <td>10</td>
      <td>347</td>
      <td>2008</td>
      <td>10</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>715</th>
      <td>11</td>
      <td>358</td>
      <td>2008</td>
      <td>10</td>
      <td>4</td>
      <td>1</td>
    </tr>
    <tr>
      <th>730</th>
      <td>12</td>
      <td>366</td>
      <td>2008</td>
      <td>10</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>824</th>
      <td>13</td>
      <td>413</td>
      <td>2008</td>
      <td>10</td>
      <td>5</td>
      <td>1</td>
    </tr>
    <tr>
      <th>846</th>
      <td>14</td>
      <td>424</td>
      <td>2008</td>
      <td>10</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>869</th>
      <td>15</td>
      <td>435</td>
      <td>2008</td>
      <td>10</td>
      <td>4</td>
      <td>1</td>
    </tr>
    <tr>
      <th>991</th>
      <td>16</td>
      <td>496</td>
      <td>2008</td>
      <td>10</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1050</th>
      <td>17</td>
      <td>526</td>
      <td>2008</td>
      <td>10</td>
      <td>5</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1092</th>
      <td>18</td>
      <td>547</td>
      <td>2008</td>
      <td>10</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1121</th>
      <td>19</td>
      <td>561</td>
      <td>2008</td>
      <td>10</td>
      <td>3</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1148</th>
      <td>20</td>
      <td>575</td>
      <td>2008</td>
      <td>10</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1233</th>
      <td>21</td>
      <td>617</td>
      <td>2008</td>
      <td>10</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1385</th>
      <td>22</td>
      <td>693</td>
      <td>2008</td>
      <td>10</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1403</th>
      <td>23</td>
      <td>702</td>
      <td>2008</td>
      <td>10</td>
      <td>4</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1435</th>
      <td>24</td>
      <td>718</td>
      <td>2008</td>
      <td>10</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1490</th>
      <td>25</td>
      <td>746</td>
      <td>2008</td>
      <td>10</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1539</th>
      <td>26</td>
      <td>770</td>
      <td>2008</td>
      <td>10</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1564</th>
      <td>27</td>
      <td>783</td>
      <td>2008</td>
      <td>10</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1578</th>
      <td>28</td>
      <td>790</td>
      <td>2008</td>
      <td>10</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1616</th>
      <td>29</td>
      <td>809</td>
      <td>2008</td>
      <td>10</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>24399</th>
      <td>26092</td>
      <td>12200</td>
      <td>2018</td>
      <td>18</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24429</th>
      <td>26093</td>
      <td>12215</td>
      <td>2018</td>
      <td>18</td>
      <td>4</td>
      <td>4</td>
    </tr>
    <tr>
      <th>24525</th>
      <td>26094</td>
      <td>12263</td>
      <td>2018</td>
      <td>18</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>24556</th>
      <td>26095</td>
      <td>12279</td>
      <td>2018</td>
      <td>18</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24596</th>
      <td>26096</td>
      <td>12299</td>
      <td>2018</td>
      <td>18</td>
      <td>5</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24628</th>
      <td>26097</td>
      <td>12315</td>
      <td>2018</td>
      <td>18</td>
      <td>4</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24692</th>
      <td>26098</td>
      <td>12347</td>
      <td>2018</td>
      <td>18</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24779</th>
      <td>26099</td>
      <td>12390</td>
      <td>2018</td>
      <td>18</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24805</th>
      <td>26100</td>
      <td>12403</td>
      <td>2018</td>
      <td>18</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24874</th>
      <td>26101</td>
      <td>12438</td>
      <td>2018</td>
      <td>18</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24932</th>
      <td>26102</td>
      <td>12467</td>
      <td>2018</td>
      <td>18</td>
      <td>2</td>
      <td>3</td>
    </tr>
    <tr>
      <th>25062</th>
      <td>26103</td>
      <td>12532</td>
      <td>2018</td>
      <td>18</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25097</th>
      <td>26104</td>
      <td>12549</td>
      <td>2018</td>
      <td>18</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>25293</th>
      <td>26105</td>
      <td>12647</td>
      <td>2018</td>
      <td>18</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>25324</th>
      <td>26106</td>
      <td>12663</td>
      <td>2018</td>
      <td>18</td>
      <td>5</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25355</th>
      <td>26107</td>
      <td>12678</td>
      <td>2018</td>
      <td>18</td>
      <td>4</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25384</th>
      <td>26108</td>
      <td>12693</td>
      <td>2018</td>
      <td>18</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25411</th>
      <td>26109</td>
      <td>12706</td>
      <td>2018</td>
      <td>18</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>25434</th>
      <td>26110</td>
      <td>12718</td>
      <td>2018</td>
      <td>18</td>
      <td>7</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25466</th>
      <td>26111</td>
      <td>12734</td>
      <td>2018</td>
      <td>18</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25526</th>
      <td>26112</td>
      <td>12764</td>
      <td>2018</td>
      <td>18</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>25572</th>
      <td>26113</td>
      <td>12787</td>
      <td>2018</td>
      <td>18</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>25740</th>
      <td>26114</td>
      <td>12871</td>
      <td>2018</td>
      <td>18</td>
      <td>3</td>
      <td>2</td>
    </tr>
    <tr>
      <th>25768</th>
      <td>26115</td>
      <td>12885</td>
      <td>2018</td>
      <td>18</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>25805</th>
      <td>26116</td>
      <td>12903</td>
      <td>2018</td>
      <td>18</td>
      <td>4</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25834</th>
      <td>26117</td>
      <td>12918</td>
      <td>2018</td>
      <td>18</td>
      <td>4</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25928</th>
      <td>26118</td>
      <td>12965</td>
      <td>2018</td>
      <td>18</td>
      <td>4</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25953</th>
      <td>26119</td>
      <td>12977</td>
      <td>2018</td>
      <td>18</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>25985</th>
      <td>26120</td>
      <td>12993</td>
      <td>2018</td>
      <td>18</td>
      <td>4</td>
      <td>1</td>
    </tr>
    <tr>
      <th>26010</th>
      <td>26121</td>
      <td>13006</td>
      <td>2018</td>
      <td>18</td>
      <td>3</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>26122 rows × 6 columns</p>
</div>